#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './config'
require_relative './lib/gitmq'

config = GitMQ::Config.new(CONFIG)
consumer = GitMQ::Consumer.new(config)

Thread.new do
  loop do
    config.storage.publish('master', Time.now)
    sleep 1
  end
end

consumer.start
