#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './config'
require_relative './lib/gittt'

WRITER = Thread.new do
  loop do
    Gittt::Storage.instance.publish(:master, Time.now)
    sleep 1
  end
end

Gittt.config = CONFIG
Gittt.read
